name: HungerGames
version: '${project.version}'
main: me.lamalditag.hungergamesulp.HungerGamesULP
api: '1.20.4'
api-version: '1.20'
commands:
  select:
    description: "Select an arena in HungerGames"
    usage: <command>
  create:
    description: "Create an arena in HungerGames"
    usage: <command>
  chestrefill:
    description: "Refills Chests an arena in HungerGames"
    usage: <command>
  supplydrop:
    description: "Drops a Supply Crate in HungerGames"
    usage: <command>
  setspawn:
    description: "Sets SpawnPoints for Arenas in HungerGames"
    usage: <command>
  start:
    description: "Starts the game in HungerGames"
    usage: <command>
  end:
    description: "Forcefully Ends the game in HungerGames"
    usage: <command>
  scanarena:
    description: "Scans the arena for chests"
    usage: <command>
  border:
    description: "Changes the world border in HungerGames"
    usage: <command> <size>
  move-toggle:
    description: "Toggles the ability to move in HungerGames"
    usage: <command>
permissions:
  hungergames.select:
    description: "Allows you to select an arena in HungerGames"
    default: op
  hungergames.create:
    description: "Allows you to create an arena in HungerGames"
    default: op
  hungergames.chestrefill:
    description: "Allows you to refill chests in HungerGames"
    default: op
  hungergames.supplydrop:
    description: "Allows you to drop a supply crate in HungerGames"
    default: op
  hungergames.setspawn:
    description: "Allows you to set spawnpoints for arenas in HungerGames"
    default: op
  hungergames.start:
    description: "Allows you to start the game in HungerGames"
    default: true
  hungergames.end:
    description: "Allows you to forcefully end the game in HungerGames"
    default: op
  hungergames.scanarena:
    description: "Allows you to scan the arena for chests in HungerGames"
    default: op
  hungergames.border:
    description: "Allows you to change the world border in HungerGames"
    default: op
  hungergames.move-toggle:
    description: "Allows you to toggle the ability to move in HungerGames"
    default: op

